name: tag a new version

on:
  workflow_dispatch:
    inputs:
      tagversion:
        description: 'Tag version'
        required: true
        type: string

      newversion:
        description: 'Next desired version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          echo this is the new tag version ${{github.event.inputs.tagversion}}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build
        run: |
          mvn clean install -DskipTests

      - name: Tag
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

          git tag -a  ${{github.event.inputs.tagversion}} -m "tag version  ${{github.event.inputs.tagversion}}"
          git push origin  ${{github.event.inputs.tagversion}}

          mvn versions:set -DnewVersion=${{github.event.inputs.newversion}}
          git commit -am "new version release ${{github.event.inputs.newversion}}"
          git push