name: build

inputs:
  tagVersion:
    description: 'Tag version'
    required: true

on:
  workflow_dispatch: { }

jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
          java -version

      - name: build testing environment
        run: |
          git clone https://github.com/mrFlick72/aws-messaging-java-client.git
          cd aws-messaging-java-client
          mvn clean install

      - name: Build
        run: |
          mvn clean install -DskipTests

      - name: Tag
        run: |
          git tag -a $INPUT_TAGVERIOSN -m "tag version $INPUT_TAGVERIOSN"
          git push origin $INPUT_TAGVERIOSN
